name = "apichain-document"
pages_build_output_dir = "public"
compatibility_date = "2025-09-05"

[build]
command = "yarn install && yarn build"

[vars]
NODE_VERSION = "20.12.0"
YARN_VERSION = "1.22.22"